config/routes.rb
Rails.application.routes.draw do
  post '/refresh', to: 'dashboard#refresh'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login/new', as: 'login'

  # get systems by department
  get 'get_systems_by_dept/:department_id', to: 'eu_exit_dash#get_systems_by_dept' 

  # get impacted systems
  get 'impact/:system_id', to: 'eu_exit_dash#impact'    

  # run create links function
  get '/create/links', to: 'system_link#generate_links'
  
  resources :sessions, only: [:create, :destroy]
  resources :protocols
  resources :agencies do
    collection do
        get 'add/:agency_name', to: 'agencies#add'
    end
  end
  resources :programs do
    collection do
        get 'add/:program_name', to: 'programs#add'
    end
  end
  resources :services
  resources :system_links do
    collection do
        get 'remove/:id', to: 'system_links#remove'
    end
  end
  resources :system_departments
  resources :systems
  resources :departments
  resources :eu_exit_dash
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/system_link.rb
class SystemLink < ApplicationRecord
	belongs_to :system_a, :class_name => 'System', inverse_of: :system_links
	belongs_to :system_b, :class_name => 'System'
	validates :system_b_id, presence: true	#removed :system_a_id as it is returned from system create
	validate :same_system_validation
	before_save :duplicate_link
	


	def same_system_validation
		if self.system_a_id == self.system_b_id
			errors.add :system_b, 'A system cannot link to itself.'
		end
	end

	def duplicate_link
		duplicate_link = SystemLink.where("system_a_id=? AND system_b_id=?", self.system_a_id, self.system_b_id) 
		if duplicate_link.exists?
			errors.add :system_b, 'System link already exists.'
		end
	end

	attribute :weight, :integer, default: 1
	#attr_accessor :system_a, :system_b, :neighbors, :weights



	def SystemLink.generate_links!
		SystemLink.where("weight > 1").destroy_all # remove previously generated links beyond the immediate direct links
		SystemLink.where("weight = 1").find_each do |link|
			link!(link.system_a, link.system_b, link.weight) # start the regression
		end
	end


	def SystemLink.link!(sys_a, sys_b, weight, previous_links=[])
		return if sys_a == nil || sys_b == nil || weight > 4 # sanity checks
		new_weight = (weight + 1) # incremented weight for new links 
		# get all links from sys B excluding any links back to sys A
		SystemLink.where(["system_a_id = ? AND system_b_id <> ?", sys_b.id, sys_a.id]).find_each do |other_link|
			previous_links = previous_links << other_link
			been_linked_before = previous_links.any? { |prev_link| # searches a collection
				# sanity check to make sure we're not doubling back on ourself 
				# exclude first el check as it will always be the same
				return true if (prev_link.system_a_id == other_link.system_a_id && prev_link.system_b_id == other_link.system_b_id && previous_links.length > 1) || (prev_link.system_b_id == other_link.system_a_id && prev_link.system_a_id == other_link.system_b_id && previous_links.length > 1)
			}
			unless been_linked_before
				new_link = SystemLink.create(system_a_id: sys_a.id, system_b_id: other_link.system_b_id, weight: new_weight, protocol: "N/A")
				if new_link.save # no collision on validator 
					link!(new_link.system_a, new_link.system_b, new_link.weight) # continue the regression
				end
			end
		end 
	end

	def SystemLink.set_importance!
		# get all of system_a_id weights and add them up
		# save to system importance variable for the system id 
		System.update_all(importance: nil)  #first update importance col to nil for all

		SystemLink.where("weight = 1").find_each do |element|
			total_importance = 0 # always reset the variable for the next id

			SystemLink.where("system_a_id = ?", element.system_a_id).find_each do |syst|
				total_importance += syst.weight  # add up all the weights for this id
			end

			# save to system db - should this error check?
			thisSystem = System.find_by(id: element.system_a_id)
			thisSystem.update(importance: total_importance)
		end
	end
end

app/controllers/system_links_controller.rb
class SystemLinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_system_link, only: [:show, :edit, :update, :destroy]


  # GET /system_links
  # GET /system_links.json
  def index
    @system_links = SystemLink.all
  end

  # GET /system_links/1
  # GET /system_links/1.json
  def show
  end

  # GET /system_links/new
  def new
    @system_link = SystemLink.new
  end

  # GET /system_links/1/edit
  def edit
  end

  # POST /system_links
  # POST /system_links.json
  def create
    @system_link = SystemLink.new(system_link_params)

    respond_to do |format|
      if @system_link.save
        format.html { redirect_to @system_link, notice: 'System link was successfully created.' }
        format.json { render :show, status: :created, location: @system_link }
      else
        format.html { render :new }
        format.json { render json: @system_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /system_links/1
  # PATCH/PUT /system_links/1.json
  def update
    respond_to do |format|
      if @system_link.update(system_link_params)
        format.html { redirect_to @system_link, notice: 'System link was successfully updated.' }
        format.json { render :show, status: :ok, location: @system_link }
      else
        format.html { render :edit }
        format.json { render json: @system_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_links/1
  # DELETE /system_links/1.json
  def destroy
    @system_link.destroy
    respond_to do |format|
      format.html { redirect_to system_links_url, notice: 'System link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # REMOVE /system_links/1
  # REMOVE /system_links/1.json
  def remove
    # remove the system link by id
    @system_link = SystemLink.where("id=?", params[:id])&.destroy_all

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system_link
      @system_link = SystemLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_link_params
      params.require(:system_link).permit(:id, :system_a_id, :system_b_id, :protocol, :weight, :systems_attributes => {})
    end

    def authenticate_user!
   redirect_to :login if current_user.nil?
  end
end

app/helpers/system_links_helper.rb
module SystemLinksHelper
end

app/views/system_links/_form.html.erb
<%= form_with(model: system_link, local: true) do |form| %>
  <% if system_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(system_link.errors.count, "error") %> prohibited this system_link from being saved:</h2>

      <ul>
      <% system_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :system_a_id, class: "govuk-label" %>
    <%= form.collection_select(:system_a_id, System.all, :id, :acronymn, {}, {class: "govuk-select"}) %>
  </div>

  <div class="field">
    <%= form.label :system_b_id, class: "govuk-label" %>
    <%= form.collection_select(:system_b_id, System.all, :id, :acronymn, {}, {class: "govuk-select"}) %>
  </div>

  <div class="field">
    <%= form.label :protocol, class: "govuk-label" %>
    <%= form.collection_select(:protocol, Protocol.all, :name, :name, {}, {class: "govuk-select"}) %>
  </div>

  <div class="field" style="display:none">
    <%= form.label :weight, class: "govuk-label" %>
    <%= form.number_field :weight, disabled: true %>
  </div>

  <div class="actions">
    <%= form.submit class: "govuk-button" %>
  </div>
<% end %>

app/views/system_links/edit.html.erb
<h1>Editing System Link</h1>

<%= render 'form', system_link: @system_link %>

<%= link_to 'Back', system_links_path %>

app/views/system_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>System Links</h1>

<table>
  <thead>
    <tr>
      <th>System a</th>
      <th>System b</th>
      <th>Protocol</th>
      <th style="display:none">Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @system_links.each do |system_link| %>
      <% next if system_link.weight > 1 %>
      <tr>
        <td><%= system_link.system_a.acronymn %></td>
        <td><%= system_link.system_b.acronymn %></td>
        <td><%= system_link.protocol %></td>
        <td style="display:none"><%= system_link.weight %></td>
        <td><%= link_to 'Edit', edit_system_link_path(system_link) %></td>
        <td><%= link_to 'Destroy', system_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Return to dashboard', root_path %>

app/views/system_links/new.html.erb
<h1>New System Link</h1>

<%= render 'form', system_link: @system_link %>

<%= link_to 'Back', system_links_path %>

app/views/system_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>System a:</strong>
  <%= @system_link.system_a.acronymn %>
</p>

<p>
  <strong>System b:</strong>
  <%= @system_link.system_b.acronymn %>
</p>

<p>
  <strong>Protocol:</strong>
  <%= @system_link.protocol %>
</p>

<p style="display:none">
  <strong>Weight:</strong>
  <%= @system_link.weight %>
</p>

<%= link_to 'Edit', edit_system_link_path(@system_link) %> |
<%= link_to 'Back', system_links_path %>