config/routes.rb
Rails.application.routes.draw do
  post '/refresh', to: 'dashboard#refresh'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login/new', as: 'login'

  # get systems by department
  get 'get_systems_by_dept/:department_id', to: 'eu_exit_dash#get_systems_by_dept' 

  # get impacted systems
  get 'impact/:system_id', to: 'eu_exit_dash#impact'    

  # run create links function
  get '/create/links', to: 'system_link#generate_links'
  
  resources :sessions, only: [:create, :destroy]
  resources :protocols
  resources :agencies do
    collection do
        get 'add/:agency_name', to: 'agencies#add'
    end
  end
  resources :programs do
    collection do
        get 'add/:program_name', to: 'programs#add'
    end
  end
  resources :services
  resources :system_links do
    collection do
        get 'remove/:id', to: 'system_links#remove'
    end
  end
  resources :system_departments
  resources :systems
  resources :departments
  resources :eu_exit_dash
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/service.rb
class Service < ApplicationRecord
	belongs_to :department, :class_name => 'Department'
	belongs_to :program, :class_name => 'Program', optional: true
	belongs_to :agency, :class_name => 'Agency', optional: true
	validates :name, presence: true, length: { minimum: 2 }, 
								uniqueness: {
								message: ->(object, data) do 
									"#{data[:value]} is in use"									
								end
							}
	validate :duplicate_service

	def duplicate_service
		duplicate_service = Service.where("name=? AND department_id=? AND program_id=? AND agency_id=?", self.name, self.department_id, self.program_id, self.agency_id) 
		if duplicate_service.exists?
			errors.add :base, 'Service already exists.'
		end
	end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    @programs = Program.all
    @agencies = Agency.all
    @program = Program.new
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    new_params = service_params.except(:program_name, :agency_name)
    @service = Service.new(new_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    new_params = service_params.except(:program_name, :agency_name)

    respond_to do |format|
      if @service.update(new_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :department_id, :program_id, :agency_id, :program_name, :agency_name)
    end

    def authenticate_user!
   redirect_to :login if current_user.nil?
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "govuk-label" %>
    <%= form.text_field :name, class: "govuk-input govuk-input--width-20" %>
  </div>

  <div class="field">
    <%= form.label :department_id, class: "govuk-label" %>
    <%= form.collection_select(:department_id, Department.all, :id, :description, {prompt: "Select a department"}, {class: "govuk-select"}) %>
  </div>

  <div class="field" id="program_select_div">
    <%= form.label :program_id, class: "govuk-label" %>
    <%= form.collection_select(:program_id, Program.all, :id, :name, {include_blank: "Select/remove a program"}, {class: "govuk-select"}) %>
    <div class="govuk-button" id="toggle_new_program">Add New Program</div>
  </div>

  <div class="field" id="program_text_div">
    <%= form.label :program_id, class: "govuk-label" %>
    <%= form.text_field :program_name, class: "govuk-input govuk-input--width-10" %>
    <div class="govuk-button" id="toggle_existing_program">Select Existing Program</div>
  </div>

  <div class="field" id="agency_select_div">
    <%= form.label :agency_id, class: "govuk-label" %>
    <%= form.collection_select(:agency_id, Agency.all, :id, :name, {include_blank: "Select/remove an agency"}, {class: "govuk-select"}) %>
    <div class="govuk-button" id="toggle_new_agency">Add New Agency</div>
  </div>

  <div class="field" id="agency_text_div">
    <%= form.label :agency_id, class: "govuk-label" %>
    <%= form.text_field :agency_name, class: "govuk-input govuk-input--width-10" %>
    <div class="govuk-button" id="toggle_existing_agency">Select Existing Agency</div>
  </div>


  <div class="actions">
    <%= form.submit class: "govuk-button" %>
  </div>

<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th style="display:none">Program</th>
      <th style="display:none">Agency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.department.description %></td>
        <td style="display:none"><%= service&.program&.name %></td>
        <td style="display:none"><%= service&.agency&.name %></td>
        <td><%= link_to 'Show', service, class: 'govuk-link govuk-link--no-visited-state' %></td>
        <td><%= link_to 'Edit', edit_service_path(service), class: 'govuk-link govuk-link--no-visited-state' %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' }, class: 'govuk-link govuk-link--no-visited-state' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path, class: 'govuk-button' %>
<br>
<%= link_to 'Return to dashboard', root_path, class: 'govuk-link govuk-link--no-visited-state' %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @service.department.description %>
</p>

<p>
  <strong>Program:</strong>
  <%= @service&.program&.name %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @service&.agency&.name %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>