config/routes.rb
Rails.application.routes.draw do
  post '/refresh', to: 'dashboard#refresh'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login/new', as: 'login'

  # get systems by department
  get 'get_systems_by_dept/:department_id', to: 'eu_exit_dash#get_systems_by_dept' 

  # get impacted systems
  get 'impact/:system_id', to: 'eu_exit_dash#impact'    

  # run create links function
  get '/create/links', to: 'system_link#generate_links'
  
  resources :sessions, only: [:create, :destroy]
  resources :protocols
  resources :agencies do
    collection do
        get 'add/:agency_name', to: 'agencies#add'
    end
  end
  resources :programs do
    collection do
        get 'add/:program_name', to: 'programs#add'
    end
  end
  resources :services
  resources :system_links do
    collection do
        get 'remove/:id', to: 'system_links#remove'
    end
  end
  resources :system_departments
  resources :systems
  resources :departments
  resources :eu_exit_dash
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :services 
	has_many :systems
	has_many :system_departments
	validates :name, presence: true,
							length: { minimum: 2 },
							uniqueness: {
								message: ->(object, data) do 
									"#{data[:value]} is in use"									
								end
							}
	validates :description, presence: true,
							length: { minimum: 2 }


							
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    # if any system department links exist then delete them as well
    @system_department = SystemDepartment.where("department_id=?", @department)&.destroy_all

    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :description)
    end

    def authenticate_user!
   redirect_to :login if current_user.nil?
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "govuk-input govuk-input--width-20" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "govuk-textarea" %>
  </div>

  <div class="actions">
    <%= form.submit class: "govuk-button" %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.description %></td>
        <td><%= link_to 'Edit', edit_department_path(department), class: 'govuk-link govuk-link--no-visited-state' %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' }, class: 'govuk-link govuk-link--no-visited-state' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path, class: 'govuk-button' %>
<br>
<%= link_to 'Return to dashboard', root_path, class: 'govuk-link govuk-link--no-visited-state' %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @department.description %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>