config/routes.rb
Rails.application.routes.draw do
  post '/refresh', to: 'dashboard#refresh'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login/new', as: 'login'

  # get systems by department
  get 'get_systems_by_dept/:department_id', to: 'eu_exit_dash#get_systems_by_dept' 

  # get impacted systems
  get 'impact/:system_id', to: 'eu_exit_dash#impact'    

  # run create links function
  get '/create/links', to: 'system_link#generate_links'
  
  resources :sessions, only: [:create, :destroy]
  resources :protocols
  resources :agencies do
    collection do
        get 'add/:agency_name', to: 'agencies#add'
    end
  end
  resources :programs do
    collection do
        get 'add/:program_name', to: 'programs#add'
    end
  end
  resources :services
  resources :system_links do
    collection do
        get 'remove/:id', to: 'system_links#remove'
    end
  end
  resources :system_departments
  resources :systems
  resources :departments
  resources :eu_exit_dash
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/protocol.rb
class Protocol < ApplicationRecord
	validates :name, presence: true,
							length: { minimum: 2 },
							uniqueness: {
								message: ->(object, data) do 
									"#{data[:value]} is in use"									
								end
							}
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_protocol, only: [:show, :edit, :update, :destroy]

  # GET /protocols
  # GET /protocols.json
  def index
    @protocols = Protocol.all
  end

  # GET /protocols/1
  # GET /protocols/1.json
  def show
  end

  # GET /protocols/new
  def new
    @protocol = Protocol.new
  end

  # GET /protocols/1/edit
  def edit
  end

  # POST /protocols
  # POST /protocols.json
  def create
    @protocol = Protocol.new(protocol_params)

    respond_to do |format|
      if @protocol.save
        format.html { redirect_to @protocol, notice: 'Protocol was successfully created.' }
        format.json { render :show, status: :created, location: @protocol }
      else
        format.html { render :new }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /protocols/1
  # PATCH/PUT /protocols/1.json
  def update
    respond_to do |format|
      if @protocol.update(protocol_params)
        format.html { redirect_to @protocol, notice: 'Protocol was successfully updated.' }
        format.json { render :show, status: :ok, location: @protocol }
      else
        format.html { render :edit }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protocols/1
  # DELETE /protocols/1.json
  def destroy
    @protocol.destroy
    respond_to do |format|
      format.html { redirect_to protocols_url, notice: 'Protocol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_protocol
      @protocol = Protocol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def protocol_params
      params.require(:protocol).permit(:name)
    end

    def authenticate_user!
   redirect_to :login if current_user.nil?
  end
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/views/protocols/_form.html.erb
<%= form_with(model: protocol, local: true) do |form| %>
  <% if protocol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(protocol.errors.count, "error") %> prohibited this protocol from being saved:</h2>

      <ul>
      <% protocol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "govuk-label" %>
    <%= form.text_field :name, class: "govuk-input govuk-input--width-20" %>
  </div>

  <div class="actions">
    <%= form.submit class: "govuk-button" %>
  </div>
<% end %>

app/views/protocols/edit.html.erb
<h1>Editing Protocol</h1>

<%= render 'form', protocol: @protocol %>

<%= link_to 'Back', protocols_path %>

app/views/protocols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Protocols</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @protocols.each do |protocol| %>
      <tr>
        <td><%= protocol.name %></td>
        <td><%= link_to 'Edit', edit_protocol_path(protocol) %></td>
        <td><%= link_to 'Destroy', protocol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Protocol', new_protocol_path, class: 'govuk-button' %>
<br>
<%= link_to 'Return to dashboard', root_path, class: 'govuk-link govuk-link--no-visited-state' %>

app/views/protocols/new.html.erb
<h1>New Protocol</h1>

<%= render 'form', protocol: @protocol %>

<%= link_to 'Back', protocols_path %>

app/views/protocols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @protocol.name %>
</p>

<%= link_to 'Edit', edit_protocol_path(@protocol) %> |
<%= link_to 'Back', protocols_path %>